//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class crfsuitePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="SWIGRegisterExceptionCallbacks_crfsuite")]
    public static extern void SWIGRegisterExceptionCallbacks_crfsuite(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_crfsuite")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_crfsuite(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_crfsuite(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_crfsuite(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(crfsuitePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(crfsuitePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="SWIGRegisterStringCallback_crfsuite")]
    public static extern void SWIGRegisterStringCallback_crfsuite(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_crfsuite(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static crfsuitePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Attribute_attr_set")]
  public static extern void Attribute_attr_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Attribute_attr_get")]
  public static extern string Attribute_attr_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Attribute_value_set")]
  public static extern void Attribute_value_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Attribute_value_get")]
  public static extern double Attribute_value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_Attribute__SWIG_0")]
  public static extern global::System.IntPtr new_Attribute__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_Attribute__SWIG_1")]
  public static extern global::System.IntPtr new_Attribute__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_Attribute__SWIG_2")]
  public static extern global::System.IntPtr new_Attribute__SWIG_2(string jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_delete_Attribute")]
  public static extern void delete_Attribute(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_Trainer")]
  public static extern global::System.IntPtr new_Trainer();

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_delete_Trainer")]
  public static extern void delete_Trainer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_clear")]
  public static extern void Trainer_clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_append")]
  public static extern void Trainer_append(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_select")]
  public static extern bool Trainer_select(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_train")]
  public static extern int Trainer_train(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_params_")]
  public static extern global::System.IntPtr Trainer_params_(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_set")]
  public static extern void Trainer_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_get")]
  public static extern string Trainer_get(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_help")]
  public static extern string Trainer_help(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_message")]
  public static extern void Trainer_message(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_messageSwigExplicitTrainer")]
  public static extern void Trainer_messageSwigExplicitTrainer(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Trainer_director_connect")]
  public static extern void Trainer_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, Trainer.SwigDelegateTrainer_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_Tagger")]
  public static extern global::System.IntPtr new_Tagger();

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_delete_Tagger")]
  public static extern void delete_Tagger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_open__SWIG_0")]
  public static extern bool Tagger_open__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_open__SWIG_1")]
  public static extern bool Tagger_open__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_close")]
  public static extern void Tagger_close(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_labels")]
  public static extern global::System.IntPtr Tagger_labels(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_tag")]
  public static extern global::System.IntPtr Tagger_tag(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_set")]
  public static extern void Tagger_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_viterbi")]
  public static extern global::System.IntPtr Tagger_viterbi(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_probability")]
  public static extern double Tagger_probability(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Tagger_marginal")]
  public static extern double Tagger_marginal(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_version")]
  public static extern string version();

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_Clear")]
  public static extern void Item_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_Add")]
  public static extern void Item_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_size")]
  public static extern uint Item_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_capacity")]
  public static extern uint Item_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_reserve")]
  public static extern void Item_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_Item__SWIG_0")]
  public static extern global::System.IntPtr new_Item__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_Item__SWIG_1")]
  public static extern global::System.IntPtr new_Item__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_Item__SWIG_2")]
  public static extern global::System.IntPtr new_Item__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_getitemcopy")]
  public static extern global::System.IntPtr Item_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_getitem")]
  public static extern global::System.IntPtr Item_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_setitem")]
  public static extern void Item_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_AddRange")]
  public static extern void Item_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_GetRange")]
  public static extern global::System.IntPtr Item_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_Insert")]
  public static extern void Item_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_InsertRange")]
  public static extern void Item_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_RemoveAt")]
  public static extern void Item_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_RemoveRange")]
  public static extern void Item_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_Repeat")]
  public static extern global::System.IntPtr Item_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_Reverse__SWIG_0")]
  public static extern void Item_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_Reverse__SWIG_1")]
  public static extern void Item_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_Item_SetRange")]
  public static extern void Item_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_delete_Item")]
  public static extern void delete_Item(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_Clear")]
  public static extern void ItemSequence_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_Add")]
  public static extern void ItemSequence_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_size")]
  public static extern uint ItemSequence_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_capacity")]
  public static extern uint ItemSequence_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_reserve")]
  public static extern void ItemSequence_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_ItemSequence__SWIG_0")]
  public static extern global::System.IntPtr new_ItemSequence__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_ItemSequence__SWIG_1")]
  public static extern global::System.IntPtr new_ItemSequence__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_ItemSequence__SWIG_2")]
  public static extern global::System.IntPtr new_ItemSequence__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_getitemcopy")]
  public static extern global::System.IntPtr ItemSequence_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_getitem")]
  public static extern global::System.IntPtr ItemSequence_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_setitem")]
  public static extern void ItemSequence_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_AddRange")]
  public static extern void ItemSequence_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_GetRange")]
  public static extern global::System.IntPtr ItemSequence_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_Insert")]
  public static extern void ItemSequence_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_InsertRange")]
  public static extern void ItemSequence_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_RemoveAt")]
  public static extern void ItemSequence_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_RemoveRange")]
  public static extern void ItemSequence_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_Repeat")]
  public static extern global::System.IntPtr ItemSequence_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_Reverse__SWIG_0")]
  public static extern void ItemSequence_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_Reverse__SWIG_1")]
  public static extern void ItemSequence_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_ItemSequence_SetRange")]
  public static extern void ItemSequence_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_delete_ItemSequence")]
  public static extern void delete_ItemSequence(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_Clear")]
  public static extern void StringList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_Add")]
  public static extern void StringList_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_size")]
  public static extern uint StringList_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_capacity")]
  public static extern uint StringList_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_reserve")]
  public static extern void StringList_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_StringList__SWIG_0")]
  public static extern global::System.IntPtr new_StringList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_StringList__SWIG_1")]
  public static extern global::System.IntPtr new_StringList__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_new_StringList__SWIG_2")]
  public static extern global::System.IntPtr new_StringList__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_getitemcopy")]
  public static extern string StringList_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_getitem")]
  public static extern string StringList_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_setitem")]
  public static extern void StringList_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_AddRange")]
  public static extern void StringList_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_GetRange")]
  public static extern global::System.IntPtr StringList_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_Insert")]
  public static extern void StringList_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_InsertRange")]
  public static extern void StringList_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_RemoveAt")]
  public static extern void StringList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_RemoveRange")]
  public static extern void StringList_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_Repeat")]
  public static extern global::System.IntPtr StringList_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_Reverse__SWIG_0")]
  public static extern void StringList_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_Reverse__SWIG_1")]
  public static extern void StringList_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_SetRange")]
  public static extern void StringList_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_Contains")]
  public static extern bool StringList_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_IndexOf")]
  public static extern int StringList_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_LastIndexOf")]
  public static extern int StringList_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_StringList_Remove")]
  public static extern bool StringList_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("crfsuite", EntryPoint="CSharp_delete_StringList")]
  public static extern void delete_StringList(global::System.Runtime.InteropServices.HandleRef jarg1);
}
