//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Item : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<Attribute>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Item(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Item obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Item() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          crfsuitePINVOKE.delete_Item(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Item(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Attribute element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Attribute this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Attribute[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Attribute[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Attribute[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<Attribute> global::System.Collections.Generic.IEnumerable<Attribute>.GetEnumerator() {
    return new ItemEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new ItemEnumerator(this);
  }

  public ItemEnumerator GetEnumerator() {
    return new ItemEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class ItemEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Attribute>
  {
    private Item collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public ItemEnumerator(Item collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Attribute Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Attribute)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    crfsuitePINVOKE.Item_Clear(swigCPtr);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(Attribute x) {
    crfsuitePINVOKE.Item_Add(swigCPtr, Attribute.getCPtr(x));
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = crfsuitePINVOKE.Item_size(swigCPtr);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = crfsuitePINVOKE.Item_capacity(swigCPtr);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    crfsuitePINVOKE.Item_reserve(swigCPtr, n);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public Item() : this(crfsuitePINVOKE.new_Item__SWIG_0(), true) {
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public Item(Item other) : this(crfsuitePINVOKE.new_Item__SWIG_1(Item.getCPtr(other)), true) {
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public Item(int capacity) : this(crfsuitePINVOKE.new_Item__SWIG_2(capacity), true) {
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  private Attribute getitemcopy(int index) {
    Attribute ret = new Attribute(crfsuitePINVOKE.Item_getitemcopy(swigCPtr, index), true);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Attribute getitem(int index) {
    Attribute ret = new Attribute(crfsuitePINVOKE.Item_getitem(swigCPtr, index), false);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Attribute val) {
    crfsuitePINVOKE.Item_setitem(swigCPtr, index, Attribute.getCPtr(val));
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(Item values) {
    crfsuitePINVOKE.Item_AddRange(swigCPtr, Item.getCPtr(values));
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public Item GetRange(int index, int count) {
    global::System.IntPtr cPtr = crfsuitePINVOKE.Item_GetRange(swigCPtr, index, count);
    Item ret = (cPtr == global::System.IntPtr.Zero) ? null : new Item(cPtr, true);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Attribute x) {
    crfsuitePINVOKE.Item_Insert(swigCPtr, index, Attribute.getCPtr(x));
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, Item values) {
    crfsuitePINVOKE.Item_InsertRange(swigCPtr, index, Item.getCPtr(values));
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    crfsuitePINVOKE.Item_RemoveAt(swigCPtr, index);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    crfsuitePINVOKE.Item_RemoveRange(swigCPtr, index, count);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public static Item Repeat(Attribute value, int count) {
    global::System.IntPtr cPtr = crfsuitePINVOKE.Item_Repeat(Attribute.getCPtr(value), count);
    Item ret = (cPtr == global::System.IntPtr.Zero) ? null : new Item(cPtr, true);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    crfsuitePINVOKE.Item_Reverse__SWIG_0(swigCPtr);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    crfsuitePINVOKE.Item_Reverse__SWIG_1(swigCPtr, index, count);
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, Item values) {
    crfsuitePINVOKE.Item_SetRange(swigCPtr, index, Item.getCPtr(values));
    if (crfsuitePINVOKE.SWIGPendingException.Pending) throw crfsuitePINVOKE.SWIGPendingException.Retrieve();
  }

}
