using BotSharp.Abstraction.Agents;
using BotSharp.Abstraction.Agents.Settings;
using BotSharp.Abstraction.Functions.Models;
using BotSharp.Plugin.AgentSkills.Services;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using System.Text.Json;

namespace BotSharp.Plugin.AgentSkills.Hooks;

/// <summary>
/// Skill function registration hook
/// Implements requirement: FR-3.1
/// </summary>
public class AgentSkillsFunctionHook : AgentHookBase
{
    public override string SelfId => "471ca181-375f-b16f-7134-5f868ecd31c6";

    private readonly ISkillService _skillService;
    private readonly ILogger<AgentSkillsFunctionHook> _logger;

    /// <summary>
    /// Constructor
    /// Implements requirement: FR-3.1
    /// </summary>
    /// <param name="services">Service provider</param>
    /// <param name="settings">Agent settings</param>
    /// <param name="skillService">Skill service</param>
    /// <param name="logger">Logger</param>
    public AgentSkillsFunctionHook(
        IServiceProvider services,
        AgentSettings settings,
        ISkillService skillService,
        ILogger<AgentSkillsFunctionHook> logger)
        : base(services, settings)
    {
        _skillService = skillService ?? throw new ArgumentNullException(nameof(skillService));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Register skill tools when functions are loaded
    /// Implements requirement: FR-3.1
    /// </summary>
    /// <param name="functions">Function list</param>
    /// <returns>Whether to continue processing</returns>
    public override bool OnFunctionsLoaded(List<FunctionDef> functions)
    {
        try
        {
            // Get tools generated by AgentSkillsDotNet
            var tools = _skillService.GetTools();

            _logger.LogDebug("Registering {Count} skill tools", tools.Count);

            // Convert to BotSharp's FunctionDef
            foreach (var tool in tools)
            {
                if (tool is AIFunction aiFunc)
                {
                    var def = new FunctionDef
                    {
                        Type = "function",
                        Name = aiFunc.Name,
                        Description = aiFunc.Description,
                        Parameters =  ConvertToFunctionParametersDef(aiFunc.JsonSchema),
                        
                    };

                    // Prevent duplicate addition
                    if (!functions.Any(f => f.Name == def.Name))
                    {
                        functions.Add(def);
                        _logger.LogDebug("Registered skill tool: {ToolName}", def.Name);
                    }
                    else
                    {
                        _logger.LogWarning("Tool {ToolName} already registered, skipping", def.Name);
                    }
                }
            }

            _logger.LogInformation("Successfully registered {Count} skill tools", tools.Count);
        }
        catch (Exception ex)
        {
            // Tool registration failure should not interrupt Agent loading
            _logger.LogError(ex, "Failed to register skill tools");
        }

        return base.OnFunctionsLoaded(functions);
    }

    /// <summary>
    /// Convert AIFunction's AdditionalProperties to FunctionParametersDef
    /// Implements requirement: FR-3.1
    /// </summary>
    /// <param name="jsonSchema">AIFunction's additional properties</param>
    /// <returns>Function parameter definition</returns>
    private FunctionParametersDef? ConvertToFunctionParametersDef(
        JsonElement jsonSchema)
    {
        try
        {
            var json = JsonSerializer.Serialize(jsonSchema);
            var doc = JsonDocument.Parse(json);

            JsonDocument? propertiesDoc = null;
            if (doc.RootElement.TryGetProperty("properties", out var propertiesElement))
            { 
                
                propertiesDoc = JsonDocument.Parse(propertiesElement.GetRawText());
            }

            return new FunctionParametersDef
            {
                Type = "object",
                Properties = propertiesDoc!,
            };
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to convert AdditionalProperties to FunctionParametersDef");
            return null;
        }
    }
}
